import { Doctor } from "@/types";

export const DOCTORS: Doctor[] = [
  {
    id: "dr-1",
    name: "Dr. Amara Osei",
    specialty: "Cardiologist",
    bio: "Board-certified cardiologist with 14 years of experience in preventive cardiology and heart failure management.",
    rating: 4.9,
    reviewCount: 312,
    experience: 14,
    avatar: "AO",
    consultationFee: 150,
    languages: ["English", "Twi"],
    availableSlots: [
      { id: "s1", time: "9:00", period: "AM" },
      { id: "s2", time: "10:00", period: "AM" },
      { id: "s3", time: "11:30", period: "AM" },
      { id: "s4", time: "2:00", period: "PM" },
      { id: "s5", time: "3:30", period: "PM" },
      { id: "s6", time: "4:30", period: "PM" },
    ],
  },
  {
    id: "dr-2",
    name: "Dr. Kwame Mensah",
    specialty: "Dermatologist",
    bio: "Specializes in medical and cosmetic dermatology, treating conditions like acne, eczema, and skin cancer screenings.",
    rating: 4.7,
    reviewCount: 198,
    experience: 9,
    avatar: "KM",
    consultationFee: 120,
    languages: ["English", "Hausa"],
    availableSlots: [
      { id: "s1", time: "8:00", period: "AM" },
      { id: "s2", time: "9:30", period: "AM" },
      { id: "s3", time: "11:00", period: "AM" },
      { id: "s4", time: "1:00", period: "PM" },
      { id: "s5", time: "2:30", period: "PM" },
      { id: "s6", time: "5:00", period: "PM" },
    ],
  },
  {
    id: "dr-3",
    name: "Dr. Fatima Al-Rashid",
    specialty: "Neurologist",
    bio: "Expert in diagnosing and treating neurological disorders including migraines, epilepsy, and Parkinson's disease.",
    rating: 4.8,
    reviewCount: 245,
    experience: 17,
    avatar: "FA",
    consultationFee: 180,
    languages: ["English", "Arabic", "French"],
    availableSlots: [
      { id: "s1", time: "10:00", period: "AM" },
      { id: "s2", time: "11:30", period: "AM" },
      { id: "s3", time: "1:30", period: "PM" },
      { id: "s4", time: "3:00", period: "PM" },
      { id: "s5", time: "4:00", period: "PM" },
    ],
  },
  {
    id: "dr-4",
    name: "Dr. Emeka Nwosu",
    specialty: "General Practitioner",
    bio: "Compassionate GP offering comprehensive primary care, preventive health screenings, and chronic disease management.",
    rating: 4.6,
    reviewCount: 421,
    experience: 11,
    avatar: "EN",
    consultationFee: 80,
    languages: ["English", "Igbo", "Yoruba"],
    availableSlots: [
      { id: "s1", time: "8:30", period: "AM" },
      { id: "s2", time: "9:00", period: "AM" },
      { id: "s3", time: "10:30", period: "AM" },
      { id: "s4", time: "12:00", period: "PM" },
      { id: "s5", time: "2:00", period: "PM" },
      { id: "s6", time: "3:00", period: "PM" },
      { id: "s7", time: "4:30", period: "PM" },
    ],
  },
  {
    id: "dr-5",
    name: "Dr. Yewande Adeyemi",
    specialty: "Pediatrician",
    bio: "Dedicated to children's health from newborns to adolescents. Specializes in developmental assessments and vaccinations.",
    rating: 4.9,
    reviewCount: 387,
    experience: 12,
    avatar: "YA",
    consultationFee: 100,
    languages: ["English", "Yoruba"],
    availableSlots: [
      { id: "s1", time: "9:00", period: "AM" },
      { id: "s2", time: "10:00", period: "AM" },
      { id: "s3", time: "11:00", period: "AM" },
      { id: "s4", time: "1:00", period: "PM" },
      { id: "s5", time: "2:30", period: "PM" },
      { id: "s6", time: "3:30", period: "PM" },
    ],
  },
  {
    id: "dr-6",
    name: "Dr. Kofi Agyemang",
    specialty: "Orthopedic Surgeon",
    bio: "Orthopedic specialist with extensive experience in sports injuries, joint replacements, and minimally invasive procedures.",
    rating: 4.8,
    reviewCount: 164,
    experience: 20,
    avatar: "KA",
    consultationFee: 200,
    languages: ["English", "Twi", "Ga"],
    availableSlots: [
      { id: "s1", time: "8:00", period: "AM" },
      { id: "s2", time: "10:00", period: "AM" },
      { id: "s3", time: "2:00", period: "PM" },
      { id: "s4", time: "4:00", period: "PM" },
    ],
  },
];

export const getDoctorById = (id: string): Doctor | undefined =>
  DOCTORS.find((d) => d.id === id);

export const SPECIALTY_COLORS: Record<string, string> = {
  Cardiologist: "bg-rose-50 text-rose-700 border-rose-200",
  Dermatologist: "bg-amber-50 text-amber-700 border-amber-200",
  Neurologist: "bg-violet-50 text-violet-700 border-violet-200",
  "General Practitioner": "bg-emerald-50 text-emerald-700 border-emerald-200",
  Pediatrician: "bg-sky-50 text-sky-700 border-sky-200",
  "Orthopedic Surgeon": "bg-orange-50 text-orange-700 border-orange-200",
};

export const AVATAR_COLORS: Record<string, string> = {
  "dr-1": "from-rose-400 to-rose-600",
  "dr-2": "from-amber-400 to-amber-600",
  "dr-3": "from-violet-400 to-violet-600",
  "dr-4": "from-emerald-400 to-emerald-600",
  "dr-5": "from-sky-400 to-sky-600",
  "dr-6": "from-orange-400 to-orange-600",
};
